---
- name: Update Bash file Server
  hosts: server
  become: yes
  tasks:
    - name: Transfer bash file to host
      ansible.builtin.copy:
        src: bash/restart_apache.sh
        dest: /bin/restart_apache.sh

    - name: Display the config
      ansible.builtin.debug:
        msg: "Config displayed"

